# Generated by Django 3.2.6 on 2025-06-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='instructor',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
