# Generated by Django 3.2.6 on 2025-06-12 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0007_alter_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warning', to='projectApp.information', verbose_name='warning')),
            ],
            options={
                'verbose_name_plural': 'WarningMessage',
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(max_length=6)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('message', models.ManyToManyField(to='projectApp.WarningMessage')),
            ],
        ),
    ]
