# Generated by Django 5.2 on 2025-06-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('loc', models.CharField(max_length=6)),
                ('Description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
