# Generated by Django 3.2.6 on 2025-06-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_event_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='instructor',
            field=models.CharField(max_length=20),
        ),
    ]
