# Generated by Django 3.2.6 on 2025-06-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0005_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='loc',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
